workflows:
  unity-ios:
    name: Unity iOS AdHoc Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      vars:
        UNITY_VERSION: 6000.0.59f2

      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.namuna.raspberrygarden

    scripts:
      # Unityインストール（GameCI）
      - name: Install Unity
        script: |
          curl -L https://github.com/game-ci/unity-install/releases/latest/download/install.sh | bash
          unity-install --version ${UNITY_VERSION}

      # Unityビルド
      - name: Build iOS
        script: |
          unity-editor \
          -batchmode -nographics -quit \
          -projectPath . \
          -buildTarget iOS \
          -executeMethod BuildScript.BuildiOS

      # IPA作成
      - name: Build IPA
        script: |
          cd build/iOS

          xcodebuild -scheme Unity-iPhone \
          -configuration Release \
          -archivePath build.xcarchive archive

          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>ad-hoc</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
          -archivePath build.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build

    artifacts:
      - build/iOS/build/*.ipa