workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable

    scripts:
      - name: Get Flutter packages
        script: |
          cd raspberry_garden
          flutter pub get

      - name: Build iOS IPA
        script: |
          cd raspberry_garden
          flutter build ipa --release

    artifacts:
      - raspberry_garden/build/ios/ipa/*.ipa